name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
         command: npm run bingSearchChrome
         browser: chrome

      - name: Copy test execution video & screenshots
        run: |
              mkdir public
              cp -r cypress/videos public/videos
              cp -r cypress/screenshots public/screenshots

      - uses: actions/upload-artifact@v3
        with:
           name: cypress-report
           path: cypress/reports/html/index.html