name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Cypress run
        uses: cypress open --config-file=cypress.config.js
      - name: Run Bing Search Test
        run: npm run bingSearchChrome