name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
         command: npm run bingSearchChrome
         browser: chrome

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
           name: cypress-screenshots
           path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
           name: cypress-videos
           path: cypress/videos